### ISSUE TITLE
[UIDS] Drawer disable scrolling of background 

### ISSUE THREAD

**Issue by domschab23** [user-interviews/ui-design-system#1100]
## Description

[Description of the problem / solution, screenshots, explanation of approach, links to docs, etc.]

The scrolling of the background should be disabled when drawer is open. Or at least there should be an option to do it via passing a prop if the scrolling is still desired in some capacity

https://github.com/user-interviews/ui-design-system/assets/54962889/485f9786-16a6-4b29-a71f-a5a4729ccaad

## User Stories

- As a [persona], I want [feature/task] so that [benefit/reason].

## Acceptance Criteria

- [Criteria 1]
- [Criteria 2]
- [Criteria 3]

## Screenshots (if applicable)

[Add screenshots, if relevant, to provide visual context.]

**Comment by gabescarbrough** [comment]
> The scrolling of the background should be disabled when drawer is open. Or at least there should be an option to do it via passing a prop if the scrolling is still desired in some capacity

You shouldn't be able to scroll the main content if the background overlay is enabled.

You should be able to scroll the main content if the background overlay is disabled.

`hasBackgroundOverlay` defaults to true but you can turn it off. The use-case for not having the overlay is for when the Drawer adds context to the page but you still want to interact with the page, like if selecting a different item changes what is in the Drawer.
