### ISSUE TITLE
Add new typography settings and default font color

### ISSUE THREAD

**Issue by rsaris** [user-interviews/ui-design-system#14]
We should add the new typography groupings from https://www.figma.com/file/471iS3QrpPtXZpS1xbsJ20/Design-System-v0?node-id=34%3A0

I imagine these will be most useful as mixins. We may want to review the ones we made for the workspace and see if we can cut them over to use this as well.

Additionally we should update our base font color to be $ux-gray-900. It may be worth looking into where we use that variable to see if we can take it out as well.

**Comment by rsaris** [comment]
As always -- we should update the rails-server to use these where we can as an example.

**Comment by jhforster** [comment]
@rsaris we can close this, yea?

**Comment by rsaris** [comment]
There is likely work to be done w.r.t. pulling this into rails-server but yeah -- we can close this.
