### ISSUE TITLE
Mobile layout for sidebars

### ISSUE THREAD

**Issue by wenzeng4** [user-interviews/ui-design-system#181]
Once we have our new layout components in the design system, there is a bug on the mobile experience with the existing components that it would be great to address.

Backstory!

Right now the layout on desktop view consists of sidebar on the right and a `pageContent` section on the left that contains both the main part of the page and a footer along the bottom. The height of the page content is  `height: calc(100vh - #{$ui-header-height} - #{$ui-navbar-height});` (seen in app/javascript/researcher/new_project_builder/layout/base_page.scss). Then the footer just sits beneath.

This causes an issue on safari mobile, because 100vh does not mean exactly the same thing it means on desktop 😅 
See https://nicolas-hoizey.com/articles/2015/02/18/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers/

Why is this an issue? Since 100vh extends past the actual viewport, it causes there to be a scroll bar on the main part of the page to scroll down to the footer. That by itself is not the end of the world, but it becomes a problem because that extra scroll bar prevents you from scrolling the inner content, the main part of the page!

It happens on a few of our pages that are still not using the new layout components, one example being the Recruit participants page. You have to be on mobile safari to see the issue:

![IMG_5833](https://user-images.githubusercontent.com/4008333/109229233-dbf4d000-7777-11eb-893f-9234d27a21ca.PNG)

But basically the inner content (the table of participants) has many rows, but is not scrollable at all on mobile 😮 .

So in the new layout components, to get around this issue and not use 100vh, we ended up just making the Footer a fixed position div along the bottom, with the main content of the page not having any height specified. 
See app/javascript/researcher/new_project_builder/layout/base_page.scss and app/javascript/common/new_layout/footer/footer.scss for where this override for the mobile case happens.

This works for the most part, but the problem arises that the content is still scrollable when the sidebar navigation is expanded. Like maybe you can see in this screenshot, I expanded the mobile sidebar and then scrolled up, and the page content peaks out at the bottom:

<img width="832" alt="Screen Shot 2021-02-25 at 2 48 06 PM" src="https://user-images.githubusercontent.com/4008333/109229707-8967e380-7778-11eb-93c1-13936b998273.png">

This is the main issue right now, that we don't want the sidebar to be scrollable at all when expanded on mobile. But there may be a few ways to solve this, including addressing the crux of the issue (the 100vh differences on mobile) in a different way.

**Comment by jasonbasuil** [comment]
Not relevant today.
