### ISSUE TITLE
Dropdowns documentation

### ISSUE THREAD

**Issue by wenzeng4** [user-interviews/ui-design-system#226]
https://docs.userinterviews.com/ui-design-system/?path=/docs/design-system-dropdown--default#when-to-use

- When to use
- When not to use 

https://docs.userinterviews.com/ui-design-system/?path=/docs/design-system-dropdown--default#formatting

- Formatting
- Best practices

**Comment by natkasman** [comment]
Thoughts on [this](https://www.notion.so/userinterviews1/Dropdowns-74e13a30f3f0486f821daa526f7771e9)? @jasonbasuil @wenzeng4

**Comment by wenzeng4** [comment]
@natkasman for some reason i can't comment in the notion, but I had two questions 

Avoid the `dropdown` component if:

`- Users can select on or many from the options` <- I'm not sure if there is a typo here but I don't quite understand what it means
-` There are more than 15 options` <- How did we decide 15? I guess having a limit is good but just wondering why 15. 

Thanks!

**Comment by jasonbasuil** [comment]
@natkasman I think this looks good! I like the last little bit about Labels along with an accompanying image as an example.

**Comment by natkasman** [comment]
> @natkasman for some reason i can't comment in the notion, but I had two questions
> 
> Avoid the `dropdown` component if:
> 
> `- Users can select on or many from the options` <- I'm not sure if there is a typo here but I don't quite understand what it means -` There are more than 15 options` <- How did we decide 15? I guess having a limit is good but just wondering why 15.
> 
> Thanks!

I referenced a few other DS and NN/g articles about Dropdowns; and ~15 seemed to be the standard/consensus.
