### ISSUE TITLE
Explore potential @babel upgrade to 7.13

### ISSUE THREAD

**Issue by jasonbasuil** [user-interviews/ui-design-system#252]
Potential solution to our dependency cascading issues? 

Also: 

"Weird! I noticed the yarn.lock seemed to update some of the webpack versions (omg dependency hell :sob:) so maybe some loader is not functioning the way it was before? Not too sure"

**Comment by rroppolo** [comment]
Going to pause this for now as it seems to require updating node to > 12.13.0 and right now we are using 12.1 for both ui-design-system and rails-server. So would require a bigger change to upgrade this atm, may do this along with the planned webpack upgrade on rails-server
