### ISSUE TITLE
Allow links in flash messages

### ISSUE THREAD

**Issue by rroppolo** [user-interviews/ui-design-system#33]
Needed for https://github.com/user-interviews/rails-server/issues/2547
This flash message contains a link.  Right now we escape all messages.

**Comment by rsaris** [comment]
As noted in the PR -- `message` in `FlashMessage` can be an element, so to accomplish this you just pass in a `<Fragment>` like we do with the COVID message (the use of `OneTimeFlash` in `app/javascript/researcher/project_builder/details.jsx`)
