### ISSUE TITLE
BUG - Double scrollbars on modals w/ small window height 

### ISSUE THREAD

**Issue by eric2523** [user-interviews/ui-design-system#341]
<img src="https://user-images.githubusercontent.com/65802187/124848799-6c2af900-df52-11eb-9d64-c88b8fcefc04.png" width=500 alt="modal" />

![image](https://user-images.githubusercontent.com/65802187/124848828-7ea53280-df52-11eb-8fd1-400fdd506edb.png)

This happens when there is a `ModalBody` with a really long height. I believe the bug is limiting the `max-height` for the `ModalBody` to `95vh`. Limiting the `ModalBody` makes it so that any `overflow-y` sets to `auto` which makes the scrollbars appear twice -- one on the ModalBody and another on the actual Modal component. 

Potential fix would be to remove `max-height` on `ModalBody`

To reproduce:
* Navigate to `http://localhost:8080/teams/plans`
* click on `Upgrade Plan` for "Pay As You Go" <img src="https://user-images.githubusercontent.com/65802187/124849725-266f3000-df54-11eb-8551-acdd49165172.png" width=300 />
* Change resolution to `1080x720`

**Comment by jasonbasuil** [comment]
Outdated. Closing
