### ISSUE TITLE
Look into adding a CHANGELOG.md

### ISSUE THREAD

**Issue by jasonbasuil** [user-interviews/ui-design-system#347]
Or figuring out a better way to document release notes for the team. I liked Storybook's release notes, wondering if we can implement something like that.

<img width="983" alt="Screen Shot 2021-07-14 at 9 41 40 AM" src="https://user-images.githubusercontent.com/37383785/125662861-e5213875-4bf1-40ef-9a81-7101ee8deab1.png">

**Comment by gabescarbrough** [comment]
We have a changelog on GH
