### ISSUE TITLE
Look into scss mixin for fade transitions

### ISSUE THREAD

**Issue by jasonbasuil** [user-interviews/ui-design-system#365]
From Rachel regarding fade transitions: 

"This is really cool. I would love to add this to the Tile component https://www.figma.com/file/471iS3QrpPtXZpS1xbsJ20/Components?node-id=5536%3A190

which isn't in the design system yet but we got a start on it in the app with the project builder start page.

https://user-images.githubusercontent.com/4008333/127717139-7e23efe8-a838-496a-a06c-c1fb4d4d50fd.png

Trying to think how we can make this reusable in both places. Right now this is a static html page so not totally sure the lift to do this in React.

Maybe a first step could be to extract it to a scss mixin to be able to be used multiple places? Perhaps taking in the initial offset height as a param?"

**Comment by gabescarbrough** [comment]
Moving away from Sass
