### ISSUE TITLE
Port over common/card components in rails-server to DS card

### ISSUE THREAD

**Issue by eric2523** [user-interviews/ui-design-system#380]
Some components that were recently ported over: https://github.com/user-interviews/rails-server/pull/7619

**Comment by eric2523** [comment]
`./Card.scss ` size `&--lg` option defaults to being as large as possible. Should this actually set the width to `$card-width` instead? @jasonbasuil

**Comment by jasonbasuil** [comment]
> `./Card.scss ` size `&--lg` option defaults to being as large as possible. Should this actually set the width to `$card-width` instead? @jasonbasuil

@eric2523 hmm, doesn't look like we're actually setting the default `&--lg` option. It makes sense that it should be set to `$card-width` like you've noticed. If you could update it that would be great!
