### ISSUE TITLE
Forms do not handle form method GET properly

### ISSUE THREAD

**Issue by rsaris** [user-interviews/ui-design-system#506]
Right now the `Form` component adds a hidden input for the method passed to `Form`. This is a necessary workaround since most browsers only support POST and GET and allows Rails routing to work properly for DELETE, PATCH, and PUT.

That said -- it breaks for GET since it does not follow the expected behavior (putting the variables into the URL etc).

Given that this is an expected way to use a form, we should update the Form component to properly handle GET as a method.

**Comment by gabescarbrough** [comment]
Resolved by https://github.com/user-interviews/ui-design-system/pull/507
